### PR TITLE
fix(processor): date year

### LINKED ISSUE #134: Fix bug in year rendering
Not sure how this happened, but the rendered year is one less than the input year!

Ah, the problem for some reason is here:

```node
> const d1 = edtf.default("2020");
undefined
> d1
2020-01-01T00:00:00.000Z
> new Intl.DateTimeFormat('en-US', { year: "numeric" }).format(d1);
"2019"
```

@inukshuk - am I doing something wrong here?

### PR DESCRIPTION
**Pull request by bdarcus**
Switch to use edtf.format.

Close: #134

### CODE REVIEW

File: src/processor.ts [hunk 1]
```diff
@@ -288,10 +292,13 @@ export class ProcReference implements ReferenceData {
 
   formatDate(date: string, options: Intl.DateTimeFormatOptions): string {
     const parsedDate = edtf.default(date);
-    const dateString = new Intl.DateTimeFormat("en-US", options).format(
-      parsedDate,
-    );
-    return dateString;
+    const year = parsedDate.year.toString();
```
Comment (bdarcus) [inline src/processor.ts:295]: This should no longer be needed, but I'll leave it there for now.
